### PR TITLE
Variable key/value handling, Nice error messages, fix #57 

### LINKED ISSUE #57: Multiple and All values are send as 'value1 + value2 + …'
Hi,

When using multiple values or All options (with auto mode), the query sent to the Warp10 datasource is like that : 
`'value1 + value2 + value3 + …' variable STORE`

Warp10 didnt like it. A best way will be to send something like : 
`'~(value1|value2|value3|…)' variable STORE`

With All option, I can override with a custom value of '~.*' but it does not work with multiple option.

### PR DESCRIPTION
**Pull request by pi-r-p**
# key/value support for variables

As Grafana allows it, the query may return a map, where keys are the checkable user friendly labels, and corresponding values hidden.

During my tests, I found out that Grafana always convert values to string, even if we deal with numbers, which is confusing for WarpScript where everything is strongly typed, so everything is now string on the WarpScript side too.

Here are the test queries:

image

And here are the generated variables, when using multi selection on testList and testMap, with "all" checked on testList:
image

And here is the WarpScript header:
```
[ '1' '2' '3' '4' '5' 'a' 'b b' ] 'testList_list' STORE
 '~' $testList_list REOPTALT + 'testList' STORE
[ 'A' '1' ] 'testMap_list' STORE
 '~' $testMap_list REOPTALT + 'testMap' STORE
[ '3' ] 'testRawStack_list' STORE
'3' 'testRawStack' STORE
LINEON
```

When user customized the "select all" value, it is used as it is in WarpScript variable. The _list variable is also created, with just the custom value, to allow scripts independent from the selection mode.
image

These changes also fixes #57 .

I think this could be easily explained in the doc, and adopted.

# Clean error display in the interface, with corrected line numbers, matching the user WarpScript.
image

### CODE REVIEW

File: src/warp10-datasource.ts [hunk 1]
```diff
@@ -183,24 +183,46 @@ export default class Warp10Datasource {
...
+          });
         }
-        // some elements on the stack, return all of them as entry
-        return res.data.map((entry, i) => {
-          return {
-            text: entry.toString() || i,
-            value: entry
-          }
-        })
+        return entries;
```
Comment (redref) [inline src/warp10-datasource.ts:237]: Nice ! Thanks for this.

File: src/warp10-datasource.ts [hunk 2]
```diff
@@ -260,24 +282,50 @@ export default class Warp10Datasource {
...
     for (let myVar of this.templateSrv.variables) {
-      let value = myVar.current.text
-
-      if (myVar.current.value != null && (myVar.current.value === '$__all' || (myVar.current.value.length === 1 && myVar.current.value[0] === '$__all')))
-      {
-        if (myVar.allValue !== null)
-          value = myVar.allValue;
-        else
-          value = myVar.options.slice(1).map(e => e.text).join(" + ");
+      let value = myVar.current.value;
```
Comment (redref) [inline src/warp10-datasource.ts]: This is a changed behavior, previouly we would have text by default.
Nevertheless, I am ok with it.

File: src/warp10-datasource.ts [hunk 3]
```diff
@@ -260,24 +282,50 @@ export default class Warp10Datasource {
...
+        // User checked the "select all" checkbox
+        if (myVar.allValue && myVar.allValue !== "") {
+          // User also defined a custom value in the variable settings
+          let customValue: String = myVar.allValue;
+          wsHeader += `[ '${customValue}' ] '${myVar.name}' STORE\n`
+          // If user already starts its custom value with ~, remove it.
+          if (customValue.startsWith("~")) {
+            customValue = customValue.slice(1);
+          }
+          wsHeader += ` '~${customValue}' '${myVar.name}_wsregexp' STORE\n`
```
Comment (redref) [inline src/warp10-datasource.ts]: I think we need to keep mapping "allValue" to the "${myVar.name}" var in order to ensure backward compatibility and user simplicity.

Globally I think,
 - "${myVar.name}" = string, allValue if defined and ticked, regexp if multi (this is consistent with current use and other Grafana DS)
 - "${myVar.name}_list = list of values (either one or multiple or all)

File: src/warp10-datasource.ts [hunk 4]
```diff
@@ -260,24 +282,50 @@ export default class Warp10Datasource {
...
+      if (Array.isArray(value) && (value.length == 1 && value[0] === '$__all')) {
+        // User checked the "select all" checkbox
+        if (myVar.allValue && myVar.allValue !== "") {
+          // User also defined a custom value in the variable settings
+          let customValue: String = myVar.allValue;
+          wsHeader += `[ '${customValue}' ] '${myVar.name}' STORE\n`
+          // If user already starts its custom value with ~, remove it.
+          if (customValue.startsWith("~")) {
+            customValue = customValue.slice(1);
+          }
```
Comment (redref) [inline src/warp10-datasource.ts]: allValue is not necessarily a regexp. We cannot assume it is.

By example, it could be a special keyword ("all") with associated timeseries and better performance results.

File: src/warp10-datasource.ts [hunk 5]
```diff
@@ -260,24 +282,50 @@ export default class Warp10Datasource {
...
+          wsHeader += ` '~${customValue}' '${myVar.name}_wsregexp' STORE\n`
+        } else {
+          // if no custom all value is defined :
+          // it means we shall create a list of all the values in WarpScript from options, ignoring "$__all" special option value. 
+          let allValues: String[] = myVar.options.filter(o => o.value !== "$__all").map(o => o.value);
+          wsHeader += `[ ${allValues.map(s => `'${s}'`).join(" ")} ] '${myVar.name}' STORE\n`; // all is stored as string in generated WarpScript.
+          //also create a ready to use regexp, suffixed by _wsregexp
+          wsHeader += ` '~' $${myVar.name} REOPTALT + '${myVar.name}_wsregexp' STORE\n`
+        }
+      } else if (Array.isArray(value)) {
```
Comment (redref) [inline src/warp10-datasource.ts:322]: Depending on Grafana version, array might contain only 1 value.

File: src/warp10-datasource.ts [hunk 6]
```diff
@@ -260,24 +282,50 @@ export default class Warp10Datasource {
...
+        wsHeader += `[ ${value.map(s => `'${s}'`).join(" ")} ] '${myVar.name}' STORE\n`; // all is stored as string in generated WarpScript.
+        //also create a ready to use regexp, suffixed by _wsregexp
+        wsHeader += ` '~' $${myVar.name} REOPTALT + '${myVar.name}_wsregexp' STORE\n`
+      } else {
+        // no multiple selection, variable is the string. As type is lost by Grafana, there is no safe way to assume something different than a string here.
+        // User can use _long or _double suffixed variable
+        wsHeader += `'${value}' '${myVar.name}' STORE\n`;
+        //additionnal conversion for WarpScript illiterates users:
+        wsHeader += ` <% $${myVar.name} TOLONG %> <% NULL %> <% %> TRY '${myVar.name}_long' STORE\n`;
+        wsHeader += ` <% $${myVar.name} TODOUBLE %> <% NULL %> <% %> TRY '${myVar.name}_double' STORE\n`;
```
Comment (redref) [inline src/warp10-datasource.ts]: Nice to have but I am not sure it is relevant. User can declare it if needed.

If we want it, we should apply it to multiple values also.

**Review by redref — CHANGES_REQUESTED** [review]

File: src/warp10-datasource.ts (hunk 3 above)
Comment (pi-r-p) [reply src/warp10-datasource.ts]: OK, I can change to this behavior. _list is for advanced users anyway.
Should I wait for other reviewers, or did you already discussed internally ?

File: src/warp10-datasource.ts (hunk 5 above)
Comment (pi-r-p) [reply src/warp10-datasource.ts:322]: With or without multi selection enabled ?

File: src/warp10-datasource.ts (hunk 6 above)
Comment (pi-r-p) [reply src/warp10-datasource.ts]: Grafana did not handle numbers as values.
I see in the code there was a special case for strings starting with 0. What was the use case ?
That's why I added _long (and _double for consistency)

File: src/warp10-datasource.ts (hunk 5 above)
Comment (redref) [reply src/warp10-datasource.ts:322]: Did not checked and do not have 5.X anymore to test. Anyway, It is safer to assume "1 value + multi == single value" and also ensure better user understanding (IMO).

File: src/warp10-datasource.ts (hunk 6 above)
Comment (redref) [reply src/warp10-datasource.ts]: Would prefer to drop it, for now, and come back to it later if needed.

Comment (redref) [reply src/warp10-datasource.ts]: > Grafana did not handle numbers as values.
> I see in the code there was a special case for strings starting with 0. What was the use case ?
> That's why I added _long (and _double for consistency)

I think, that was to force escaping in JS templating (in case value was numeric).

File: src/warp10-datasource.ts (hunk 5 above)
Comment (pi-r-p) [reply src/warp10-datasource.ts:322]: done like this.

File: src/warp10-datasource.ts (hunk 6 above)
Comment (pi-r-p) [reply src/warp10-datasource.ts]: removed

File: src/warp10-datasource.ts (hunk 4 above)
Comment (pi-r-p) [reply src/warp10-datasource.ts]: ok, done like this.

File: src/warp10-datasource.ts (hunk 3 above)
Comment (pi-r-p) [reply src/warp10-datasource.ts]: Now clearer. 
varname and varname_list are always defined, that is consistent.

**Comment by pi-r-p** [comment]
Waiting for your approval before updating the README.

**Comment by redref** [comment]
@pi-r-p : Will run some tests later on, but I agree with concepts !

**Comment by miton18** [comment]
@pi-r-p Can you check the behaviour with the panel-repeat feature ?

**Comment by pi-r-p** [comment]
README update... Took more time than coding.
While trying the simplified mode, I found a little bug around advancedMode I also fixed with 
51dd392 .

**Comment by pi-r-p** [comment]
> @pi-r-p Can you check the behaviour with the panel-repeat feature ?

If you explained me what it is and a use case, I can check... But I do prefer you check with a real use case ^^

**Comment by redref** [comment]
> > @pi-r-p Can you check the behaviour with the panel-repeat feature ?
> 
> If you explained me what it is and a use case, I can check... But I do prefer you check with a real use case ^^

I checked it on my side and it is Ok. All other checks are also ok (non-exhaustive, but real use cases).

**Review by redref — APPROVED** [review]

**Comment by redref** [comment]
@pi-r-p : Seems ok to me, will wait @miton18 and run some final tests before merging. Anything to append ?

**Comment by pi-r-p** [comment]
@redref : nothing to add/fix for the moment. 
I am very new to Grafana...
I didn't use / test the world map, I hope there is no side effect.

A missing feature I see is a way to generate markdown in WarpScript that will be displayed in a panel. Just like the Text panel, but with a query. I didn't look at how to build a custom panel. Maybe it is not possible in a datasource plugin.

File: README.md [hunk 7]
```diff
@@ -11,39 +11,62 @@ Grafana will use the *dist/* folder by default
...
+You will see at the beginning of the query some special variables set by the plugin.
+
+
+| Name          | Description                                                   | Example                    |
+|---------------|---------------------------------------------------------------|----------------------------|
+| **$end**      | Timestamp of the most recent point in the Grafana time window | 1498038153276000           |
+| **$endISO**   | *end* value in ISO-8601 format                                | '2017-06-21T09:42:33.276Z' |
+| **$start**    | Timestamp of the less recent point in the Grafana time window | 1498034553276000           |
+| **$startISO** | *start* value in ISO-8601 format                              | '2017-06-21T08:42:33.276Z' |
+| **$interval** | Difference between $end and $start                            | 3600000000                 |
```
Comment (miton18) [inline README.md:50]: missing `$__interval`

File: README.md [hunk 8]
```diff
@@ -174,9 +227,28 @@ To understand the variable resolution, this is how a query is built
...
+
+[ $rt '~beertender.(rawvalue|rawoffset)' {} $end $interval ] FETCH 
+'rawResult' STORE
+
+[ $rawResult [] 'beertender.rawvalue' filter.byclass ] FILTER 0 GET 'rawvalue' STORE
+
+// empty : 30.68e6
+// full (hot): 30.45e6
+// full (cold): 30.475e6
+30.8e6  $rawvalue - [ SWAP 0 mapper.max.x 0 0 0 ] MAP 0 GET
```
Comment (miton18) [inline README.md]: Can you explain what you do ?

File: src/warp10-datasource.ts [hunk 9]
```diff
@@ -90,10 +90,17 @@ export default class Warp10Datasource {
         return { data }
       })
       .catch((err) => {
-        console.warn('[Warp 10] Failed to execute query', err)
+        let headers = err.headers();
+        let wsHeadersOffset: number = wsHeader.split('\n').length;
+        let errorline: number = Number.parseInt(headers['x-warp10-error-line']) - wsHeadersOffset;
```
Comment (miton18) [inline src/warp10-datasource.ts]: `try {} catch {}` because __parseInt__ can fail

File: src/warp10-datasource.ts [hunk 10]
```diff
@@ -90,10 +90,17 @@ export default class Warp10Datasource {
         return { data }
       })
       .catch((err) => {
-        console.warn('[Warp 10] Failed to execute query', err)
+        let headers = err.headers();
```
Comment (miton18) [inline src/warp10-datasource.ts]: const

File: src/warp10-datasource.ts [hunk 11]
```diff
@@ -90,10 +90,17 @@ export default class Warp10Datasource {
...
+        let wsHeadersOffset: number = wsHeader.split('\n').length;
```
Comment (miton18) [inline src/warp10-datasource.ts]: const

File: src/warp10-datasource.ts (hunk 9 above)
Comment (miton18) [inline src/warp10-datasource.ts]: const

File: src/warp10-datasource.ts [hunk 12]
```diff
@@ -183,24 +190,46 @@ export default class Warp10Datasource {
...
-            })
-          })
-          return entries
+        // Grafana can handle different text/value for the variable drop list. User has three possibilites in the WarpScript result:
+        // 1 - let a list on the stack : text = value for each entry. 
+        // 2 - let a map on the stack : text = map key, value = map value. value will be used in the WarpScript variable.
+        // 3 - let some strings or numbers on the stack : it will be considered as a list, refer to case 1.
+        // Values could be strings or number, ignore other objects.
+
+        let entries = [];
```
Comment (miton18) [inline src/warp10-datasource.ts:204]: const

File: src/warp10-datasource.ts [hunk 13]
```diff
@@ -183,24 +190,46 @@ export default class Warp10Datasource {
...
+          // case 1
+          res.data[0].forEach(elt => {
+            if (typeof elt === 'string' || elt instanceof String || typeof elt === 'number') {
+              entries.push({
+                text: elt.toString(),
+                value: elt.toString() // Grafana will turn every value to strings anyway !
+              })
+            }
+          });
+        } else if (res.data.length === 1 && typeof res.data[0] === 'object') {
```
Comment (miton18) [inline src/warp10-datasource.ts:215]: Can you choose only 1 operand order ? (line 200)

File: src/warp10-datasource.ts [hunk 14]
```diff
@@ -183,24 +190,46 @@ export default class Warp10Datasource {
...
+          // case 2
+          Object.keys(res.data[0]).forEach(key => {
```
Comment (miton18) [inline src/warp10-datasource.ts:217]: When you want both key and value of an object, you can use https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/entries

File: src/warp10-datasource.ts [hunk 15]
```diff
@@ -260,24 +289,51 @@ export default class Warp10Datasource {
         value = value.replace(/'/g, '"')
       if (typeof value === 'string' && !value.startsWith('<%') && !value.endsWith('%>'))
         value = `'${value}'`
-      wsHeader += `${value || 'NULL'} '${myVar}' STORE `
+      wsHeader += `${value || 'NULL'} '${myVar}' STORE\n`
     }
     // Dashboad templating vars
+    // current.text is the label. In case of multivalue, it is a string 'valueA + valueB'
+    // current.value is a string, depending on query output. In case of multivalue, it is an array of strings. array contains "$__all" if user selects All.
+    //console.log("this.templateSrv.variables", this.templateSrv.variables)
```
Comment (miton18) [inline src/warp10-datasource.ts]: you can drop this comment (l. 297)

File: src/warp10-datasource.ts [hunk 16]
```diff
@@ -260,24 +289,51 @@ export default class Warp10Datasource {
...
     for (let myVar of this.templateSrv.variables) {
-      let value = myVar.current.text
-
-      if (myVar.current.value != null && (myVar.current.value === '$__all' || (myVar.current.value.length === 1 && myVar.current.value[0] === '$__all')))
-      {
-        if (myVar.allValue !== null)
-          value = myVar.allValue;
-        else
-          value = myVar.options.slice(1).map(e => e.text).join(" + ");
+      let value = myVar.current.value;
```
Comment (miton18) [inline src/warp10-datasource.ts]: const

File: src/warp10-datasource.ts [hunk 17]
```diff
@@ -260,24 +289,51 @@ export default class Warp10Datasource {
...
+
+      if (Array.isArray(value) && (value.length == 1 && value[0] === '$__all')) {
+        // User checked the "select all" checkbox
+        if (myVar.allValue && myVar.allValue !== "") {
+          // User also defined a custom value in the variable settings
+          let customValue: String = myVar.allValue;
```
Comment (miton18) [inline src/warp10-datasource.ts]: const

File: src/warp10-datasource.ts [hunk 18]
```diff
@@ -260,24 +289,51 @@ export default class Warp10Datasource {
...
+          wsHeader += `[ '${customValue}' ] '${myVar.name}_list' STORE\n`
+          // custom all value is taken as it is. User may or may not use a regexp.
+          wsHeader += ` '${customValue}' '${myVar.name}' STORE\n`
+        } else {
+          // if no custom all value is defined :
+          // it means we shall create a list of all the values in WarpScript from options, ignoring "$__all" special option value. 
+          let allValues: String[] = myVar.options.filter(o => o.value !== "$__all").map(o => o.value);
```
Comment (miton18) [inline src/warp10-datasource.ts]: const

**Review by miton18 — CHANGES_REQUESTED** [review]

File: README.md (hunk 7 above)
Comment (pi-r-p) [reply README.md:50]: It wasn't inside the original table too... I don't understand the point of this variable. What is the use case ?

File: README.md (hunk 8 above)
Comment (pi-r-p) [reply README.md]: I will, with a few comments.

File: src/warp10-datasource.ts (hunk 9 above)
Comment (pi-r-p) [reply src/warp10-datasource.ts]: By construction in Warp 10, it cannot fail, as long as it is really here... 
There is a way to set a different header name in Warp 10 configuration, but it is not exposed.
To be sure, I will check the existence of both headers before.

File: src/warp10-datasource.ts (hunk 14 above)
Comment (pi-r-p) [reply src/warp10-datasource.ts:217]: That's what I did first entries().foreach( (k,v) =>{}), but it fails with the latest firefox. I don't want to add a polyfill for just this...

File: README.md (hunk 7 above)
Comment (miton18) [reply README.md:50]: Yes, it has been forgot, this is a Grafana defined variable
https://grafana.com/docs/grafana/latest/reference/templating/#the-interval-variable

**Review by miton18 — APPROVED** [review]

**Comment by miton18** [comment]
> will wait @miton18 and run some final tests before merging. Anything to append ?

Approuved, @redref we can merge it if your final tests are OK
